/*
 * I_Directory_Administration
 * REST Schnittstelle zur Pflege der Verzeichniseinträge. Über diese Schnittstelle können Verzeichniseinträge inklusive Zertifikaten erzeugt, aktualisiert und gelöscht werden. Die Administration von Fachdaten erfolgt über Schnittstelle I_Directory_Application_Maintenance und wird durch die Fachanwendungen durchgeführt. Lesender Zugriff auf die Fachdaten ist mit Operation getDirectoryEntries in vorliegender Schnittstelle möglich.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.gematik.ti.epa.vzd.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.gematik.ti.epa.vzd.client.model.BaseDirectoryEntry;
import de.gematik.ti.epa.vzd.client.model.Fachdaten;
import de.gematik.ti.epa.vzd.client.model.UserCertificate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DirectoryEntry
 */
public class DirectoryEntryTest {

    private final DirectoryEntry model = new DirectoryEntry();

    /**
     * Model tests for DirectoryEntry
     */
    @Test
    public void testDirectoryEntry() {
        // TODO: test DirectoryEntry
    }

    /**
     * Test the property 'directoryEntryBase'
     */
    @Test
    public void directoryEntryBaseTest() {
        // TODO: test directoryEntryBase
    }

    /**
     * Test the property 'userCertificates'
     */
    @Test
    public void userCertificatesTest() {
        // TODO: test userCertificates
    }

    /**
     * Test the property 'fachdaten'
     */
    @Test
    public void fachdatenTest() {
        // TODO: test fachdaten
    }

}
