/*
 * I_Directory_Administration
 * REST Schnittstelle zur Pflege der Verzeichniseinträge. Über diese Schnittstelle können Verzeichniseinträge inklusive Zertifikaten erzeugt, aktualisiert und gelöscht werden. Die Administration von Fachdaten erfolgt über Schnittstelle I_Directory_Application_Maintenance und wird durch die Fachanwendungen durchgeführt. Lesender Zugriff auf die Fachdaten ist mit Operation getDirectoryEntries in vorliegender Schnittstelle möglich.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.gematik.ti.epa.vzd.client.model;

import org.junit.Test;


/**
 * Model tests for Fachdaten
 */
public class FachdatenTest {

    private final Fachdaten model = new Fachdaten();

    /**
     * Model tests for Fachdaten
     */
    @Test
    public void testFachdaten() {
        // TODO: test Fachdaten
    }

    /**
     * Test the property 'dn'
     */
    @Test
    public void dnTest() {
        // TODO: test dn
    }

    /**
     * Test the property 'FAD1'
     */
    @Test
    public void FAD1Test() {
        // TODO: test FAD1
    }

}
