/*
 * I_Directory_Administration
 * REST Schnittstelle zur Pflege der Verzeichniseinträge. Über diese Schnittstelle können Verzeichniseinträge inklusive Zertifikaten erzeugt, aktualisiert und gelöscht werden. Die Administration von Fachdaten erfolgt über Schnittstelle I_Directory_Application_Maintenance und wird durch die Fachanwendungen durchgeführt. Lesender Zugriff auf die Fachdaten ist mit Operation getDirectoryEntries in vorliegender Schnittstelle möglich.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.gematik.ti.epa.vzd.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import de.gematik.ti.epa.vzd.client.model.DistinguishedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for UserCertificate
 */
public class UserCertificateTest {

    private final UserCertificate model = new UserCertificate();

    /**
     * Model tests for UserCertificate
     */
    @Test
    public void testUserCertificate() {
        // TODO: test UserCertificate
    }

    /**
     * Test the property 'dn'
     */
    @Test
    public void dnTest() {
        // TODO: test dn
    }

    /**
     * Test the property 'entryType'
     */
    @Test
    public void entryTypeTest() {
        // TODO: test entryType
    }

    /**
     * Test the property 'telematikID'
     */
    @Test
    public void telematikIDTest() {
        // TODO: test telematikID
    }

    /**
     * Test the property 'professionOID'
     */
    @Test
    public void professionOIDTest() {
        // TODO: test professionOID
    }

    /**
     * Test the property 'usage'
     */
    @Test
    public void usageTest() {
        // TODO: test usage
    }

    /**
     * Test the property 'userCertificate'
     */
    @Test
    public void userCertificateTest() {
        // TODO: test userCertificate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

}
